### ISSUE TITLE
Request: alps.wtf support

### ISSUE THREAD

**Issue by benbodhi** [JoeCars/Nerman.js#64]
Would love to have Alps support in here. Hopefully it's not too much lift to add since Alps is a fork of nouns pre-fork mechanism, so most of the nouns code in Nerman can probably be reused.
Thank you thank you!

You can get all the contract addresses here: https://about.alps.wtf/contracts/alps-contracts

alps.wtf

**Comment by benbodhi** [comment]
looking deeper in the repo, the simplest solution is probably to duplicate and modify the lil nouns integration as it is very similar, being a fork of nouns as well.

**Comment by sobhan-m** [comment]
Really appreciate the suggestion, so we went ahead and added support for the Alps contracts with the latest pull request #66 . You should have access to the event listeners and associated types now.

Installation:
```
npm install --save nerman@alpha
```

Use:
```ts
import { Alps } from "nerman";

const alps = new Alps("<Your JSON_RPC_URL>");
alps.on("AlpCreated", ({ tokenId, seed, event }) => {
   console.log(`Alp ${tokenId} created!`);
});
```

Let us know if you have any questions or other suggestions. We are likely to add these events to the Nerman Feeds bot as well in the coming week.

**Comment by benbodhi** [comment]
Epic! Thanks so much legends 🙏
